### ISSUE TITLE
`make update-pregenerated` doesn't update checked-in files

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart-protoc-plugin#61]
Looking at https://github.com/dart-lang/dart-protoc-plugin/commit/c6b927d8b882d5a913f8fa36e62ecf6ec1435913

Files created:

```
lib/src/descriptor.pbjson.dart
lib/src/descriptor.pbserver.dart
lib/src/plugin.pbenum.dart
lib/src/plugin.pbjson.dart
lib/src/plugin.pbserver.dart
```

**Comment by jakobr-google** [comment]
Running `make update-pregenerated` does update the pregenerated files (well, for me, at least). In this case, I'm guessing there just weren't any changes, so the updated files matched the current files.

The extra files created are there because we've later split out the enums, json constants, and server code. And we generate those files even if they're empty, which seems kind of silly.
